# tasks file for zabbix_memory_usage
  - name: Install the package "python"
    apt: name={{item}} state=present
    with_items:
      - python

  - name: Add python dependencies
    pip: name={{item}} state=present
    with_items:
      - pyzabbix

  - name: Make /var/lib/zabbix directory
    file: name=/var/lib/zabbix state=directory

  - name: Copy zabbix_memory.py script
    copy: src={{role_path}}/templates/zabbix_memory.py 
          dest=/var/lib/zabbix/zabbix_memory.py
          mode="u=rwx,g=rx,o=rx"

  - name: Add userparameter settings
    template: src=userparameter_linux_memory.conf
              dest=/etc/zabbix/zabbix_agentd.d/userparameter_linux_memory.conf
    notify:
      - restart zabbix agent
